#!/bin/bash

`rm ./js/compiled.js`
scripts=("/js/constants.js" "/js/util.js" "/js/messages/Messages.js" "/js/animation/Animator.js" "/js/animation/Frames.js" "/js/animation/FramesBuilder.js" "/js/obstacles/Obstacle.js" "/js/obstacles/Obstacles.js" "/js/sounds/Sounds.js" "/js/obstacles/ObstaclesBuilder.js" "/js/characters/CharacterProperties.js" "/js/characters/CharacterPropertiesBuilder.js" "/js/characters/Character.js" "/js/characters/CharacterBuilder.js" "/js/events/Events.js" "/js/game/GameBoard.js" "/js/game/GameBoardBuilder.js" "/js/game/Game.js" "/js/game/Fighting.js" "/js/gameConfiguration.js")

for s in ${scripts[@]}; do
    echo $s
    `cat .$s >> ./js/compiled.js`
done
