// labels
var STOP_POSITION = 'STOP_POSITION';
var RIGHT_HEIGHT = 'RIGHT_HEIGHT';
var LEFT_HEIGHT = 'LEFT_HEIGHT';
var ACTION = 'ACTION';
var DIRECTION = 'DIRECTION';
var SPRITE = 'SPRITE';
var FRAMES = 'FRAMES';
var ANIMATION = 'ANIMATION';
var NAME = 'NAME';
var HEIGHT_OFFSET = 'HEIGHT_OFFSET';
var FPS = 'FPS';
var PIXELS_PER_SECOND = 'PIXELS_PER_SECOND';
var CURRENT_PIXELS_PER_SECOND = 'CURRENT_PIXELS_PER_SECOND';
var STATUS = 'STATUS';
var ALIVE = 'ALIVE';
var DEAD = 'DEAD';
var ATTACK_THRESHOLDS = 'ATTACK_THRESHOLDS';
var TURNAROUND = 'TURNAROUND';
var MIN = 'MIN';
var MAX = 'MAX';
var DELAY = 'DELAY';
var POSITIONS = 'POSITIONS';

// Actions
var STOP = 'STOP';
var RUN = 'RUN';
var ATTACK = 'ATTACK';
var JUMP = 'JUMP';
var WALK = 'WALK';
var HAS_MOVING_ATTACK = 'HAS_MOVING_ATTACK';
var DEATH = 'DEATH';
var ATTACK_PROXIMITY = 300;

// Directions
var LEFT = 'LEFT';
var RIGHT = 'RIGHT';

// Sprites
var BARBARIAN_SPRITE_NAME = 'BARBARIAN';
var MONSTER_SPRITE_NAME = 'MONSTER';

