// dimensions
var SCREEN_HEIGHT = 800;
var SCREEN_WIDTH = 1400;

var RUN_SPEED_INCREASE_FACTOR = 1.5;
var DEFAULT_DEATH_DELAY = 2000;

var ADVANCE_SCREEN_SCROLL_DURATION = 1000;
var ADVANCE_SCREEN_PIXELS_PER_SECOND = 1500;
var ADVANCE_SCREEN_PIXELS_PER_FRAME = 10;

// labels
var OBSTACLE_TYPE = 'OBSTACLE_TYPE';
var PIT = 'PIT';
var ELEVATION = 'ELEVATION';
var FAIL_ACTION = 'FAIL_ACTION';
var JUMP_RANGE = 'JUMP_RANGE';
var TIMESTAMP = 'TIMESTAMP';
var STEP = 'STEP';
var FALL = 'FALL';
var HEIGHT = 'HEIGHT';
var CONSEQUENCE = 'CONSEQUENCE';
var STOP_POSITION = 'STOP_POSITION';
var RIGHT_HEIGHT = 'RIGHT_HEIGHT';
var LEFT_HEIGHT = 'LEFT_HEIGHT';
var ACTION = 'ACTION';
var DIRECTION = 'DIRECTION';
var SPRITE = 'SPRITE';
var FRAMES = 'FRAMES';
var ANIMATION = 'ANIMATION';
var NAME = 'NAME';
var HEIGHT_OFFSET = 'HEIGHT_OFFSET';
var FPS = 'FPS';
var PIXELS_PER_SECOND = 'PIXELS_PER_SECOND';
var STATUS = 'STATUS';
var ALIVE = 'ALIVE';
var DEAD = 'DEAD';
var ATTACK_THRESHOLDS = 'ATTACK_THRESHOLDS';
var BARBARIAN_ATTACK_THRESHOLDS = 'BARBARIAN_ATTACK_THRESHOLDS';
var TURNAROUND = 'TURNAROUND';
var MIN = 'MIN';
var MAX = 'MAX';
var DELAY = 'DELAY';
var POSITIONS = 'POSITIONS';
var OBSTACLES = 'OBSTACLES';
var OPPONENTS = 'OPPONENTS';
var DEATH_TIME = 'DEATH_TIME';

// Actions
var STOP = 'STOP';
var RUN = 'RUN';
var ATTACK = 'ATTACK';
var JUMP = 'JUMP';
var WALK = 'WALK';
var HAS_MOVING_ATTACK = 'HAS_MOVING_ATTACK';
var DEATH = 'DEATH';
var SIT = 'SIT';
var ATTACK_PROXIMITY = 320;

// Directions
var LEFT = 'LEFT';
var RIGHT = 'RIGHT';

// Sprites
var BARBARIAN_SPRITE_NAME = 'BARBARIAN';
var MONSTER_SPRITE_NAME = 'MONSTER';
var DOG_SPRITE_NAME = 'DOG';

